### ISSUE TITLE
Coordinator doesn't approve milstones

### ISSUE THREAD

**Issue by dobroleks94** [iotaledger/hornet#1003]
When I deploy new private tangle as [this](https://docs.iota.org/docs/hornet/1.1/tutorials/one-click-private-tangle) tutorial proposes, I have 3 nodes: Spammer, Coordinator and simple user node. Till the 30th of March - everything did look fine, but accidentally Coordinator was crashed. After many attempts of reloading, reinstalling, Coordinator refuses approve new milestone right after my custom node is synchronized with Coo. It just throws following exception:
`failed to create: signature validation failed: %!w(<nil>)` 
Does anybody have an idea what this means?

**Comment by muXxer** [comment]
It means the milestones in you network don't fit the configured coordinator address in your config file.
Easiest way would be to start with a fresh network. Delete all the databases of all nodes and bootstrap your network.

I would also recommend to use the latest develop version of HORNET, since all the breaking IOTA protocol changes in there will be live soon.
