### ISSUE TITLE
Peers: Permanently block unknown peers

### ISSUE THREAD

**Issue by miili** [iotaledger/hornet#1069]
**Is your feature request related to a problem? Please describe.**
Deleted peers re-appear.

**Describe the solution you'd like**
Permanently block unknown and unwanted peers. Introduce a peer blacklist.

**Comment by Travetown** [comment]
You can set this parameter to 0 in the config.  "gossipUnknownPeersLimit": 4

**Comment by muXxer** [comment]
Thanks for the suggestion, but I don't want to make things more complicated for the user.
A denylist also means we need to store that info somewhere, and we need to handle what happens if the user accidentally blocked a peer etc. Where should denied peers be listed, etc etc.

I would suggest to go the way Travetown proposed. Set `gossipUnknownPeersLimit` to zero, then you only get added peers.
