### ISSUE TITLE
Problems while docker-compose up

### ISSUE THREAD

**Issue by HenS1** [iotaledger/hornet#1070]
Im new to this, but here is a short description.

I downloaded the Repo and made an docker-compose up. All fine, but then the CMD holds me that it is not able to download the snapshots. So I download them manually. But then this error appears 

hornet_1  | 2021-05-01T19:42:40Z	PANIC	Snapshot	snapshot/core.go:162	no download URL specified for snapshot files in config
hornet_1  | github.com/gohornet/hornet/core/snapshot.configure
hornet_1  | 	/app/core/snapshot/core.go:162
hornet_1  | github.com/gohornet/hornet/pkg/node.(*Node).configure.func1
hornet_1  | 	/app/pkg/node/node.go:212
hornet_1  | github.com/gohornet/hornet/pkg/node.forEachCorePlugin
hornet_1  | 	/app/pkg/node/node.go:320
hornet_1  | github.com/gohornet/hornet/pkg/node.(*Node).ForEachCorePlugin
hornet_1  | 	/app/pkg/node/node.go:328
hornet_1  | github.com/gohornet/hornet/pkg/node.(*Node).configure
hornet_1  | 	/app/pkg/node/node.go:210
hornet_1  | github.com/gohornet/hornet/pkg/node.New
hornet_1  | 	/app/pkg/node/node.go:49
hornet_1  | github.com/gohornet/hornet/pkg/node.Run
hornet_1  | 	/app/pkg/node/node.go:62
hornet_1  | main.main
hornet_1  | 	/app/main.go:33
hornet_1  | runtime.main
hornet_1  | 	/usr/local/go/src/runtime/proc.go:225
hornet_1  | panic: no download URL specified for snapshot files in config
hornet_1  |

**Comment by HenS1** [comment]
my config.json

"snapshots": {
    "depth": 50,
    "interval": 200,
    "fullPath": "snapshots/mainnet/full_snapshot.bin",
    "deltaPath": "snapshots/mainnet/delta_snapshot.bin",
    "deltaSizeThresholdPercentage": 50.0,
    "downloadURLs": [
      {
        "full": "https://chrysalis-dbfiles.iota.org/snapshots/hornet/latest-full_snapshot.bin",
        "delta": "https://chrysalis-dbfiles.iota.org/snapshots/hornet/latest-delta_snapshot.bin"
      }
    ]
  },

**Comment by cloud-versity** [comment]
Hi Devinee,

this issue is already fixed it just didn't make it to the main branch yet.

https://github.com/gohornet/hornet/pull/1068 
https://github.com/gohornet/hornet/issues/1062

Though, they already got merged into develop. The following would be a workaround:

1. Clone the repo
2. Checkout develop
3. docker build -f docker/Dockerfile -t hornet:develop . 
4. Change your docker-compose.yaml image to the one, you built in step 3.

The permissions of the snapshot and database directory changed as well. Be sure to create them beforehand with the following permissions:

sudo mkdir mainnetdb && sudo chown 65532:65532 mainnetdb
sudo mkdir -p snapshots/mainnet && sudo chown 65532:65532 snapshots -R

Kind regards, 
Stephan

PS: You'll probably encounter the same frontend bug as I do. You can't add peering partner in the frontend. You'll receive a 403 forbidden thingy. So either you configure it through the peering.json file or you need to ask your peering partner to add you instead.

**Comment by Ephaltes** [comment]
> PS: You'll probably encounter the same frontend bug as I do. You can't add peering partner in the frontend. You'll receive a 403 forbidden thingy. So either you configure it through the peering.json file or you need to ask your peering partner to add you instead.

I also had this error my problem was that in the config.json , the problem was that I deleted the IPv6 whitelist

so with 

`"whitelistedAddresses": [
      "127.0.0.1",
	  "::1"
    ],`
    
   it is working but with 
    `"whitelistedAddresses": [
      "127.0.0.1"
    ],` 
it is not working

**Comment by muXxer** [comment]
Guess this can be closed? :)
