### ISSUE TITLE
Logged out after restart, /auth HTTP 429

### ISSUE THREAD

**Issue by ChristopherWalz** [iotaledger/hornet#1130]
**Describe the bug**
My pruning `"targetSize"` was set to 30GB (on a 40GB ssd) and I was running on 93% of device space, so I decided to set it to 25GB and restart hornet.
After restarting hornet, I got logged out from the dashboard and cannot login, since /auth gives me HTTP 429 all the time.

Pruning config:
``
 "pruning": {
    "milestones": {
      "enabled": false,
      "maxMilestonesToKeep": 60480
    },
    "size": {
      "enabled": true,
      "targetSize": "25GB",
      "thresholdPercentage": 10.0,
      "cooldownTime": "5m"
    },
    "pruneReceipts": false
  },
``

**Environment information:**
CPX11
2VCPU
2 GB RAM
40 GB DISK LOKAL
 - HORNET version 1.0.2

**Additional context**
Log since restarting: https://gist.github.com/ChristopherWalz/5bb661b6f569d0dfc7bfe072568d9bca

**Comment by ChristopherWalz** [comment]
After some time the logins appears to work again, but then after refreshing the page I will get a HTTP 429 again.

**Comment by ChristopherWalz** [comment]
Also according to the log the pruning seems to work, my hornet db is still getting bigger. After restarting the server with 25GB treshold, the database was 28.5 GB, right now its 29.13 GB.

How does the treshold work and if the treshold percentage is 10%, shouldn't it stop after 27.5 GB max?

**Comment by muXxer** [comment]
The `/auth` endpoint is protected by rate limiting. This way no one can brute force the password.
Do you have multiple dashboard tabs open? Why do you refresh the page? This would always trigger the rate limiting.
```go
    Rate:      rate.Limit(1 / 300.0), // 1 request every 5 minutes
    Burst:     10,                    // additional burst of 10 requests
    ExpiresIn: 5 * time.Minute,
``` 

Pruning starts at `25GB` and tries to prune and guesses the amount of milestones to prune, to achieve `22,5GB` (10%) less disc space. But this is only a target, and not hard capped. The database engine will itself do some magic, which we can't control. If the database engine decides to do a compaction, the size will increase because new files are created during compaction, data is copied over and then finally the old files are deleted and the space is freed. Which database engine do you use? We recommend rocksdb.

**Comment by ChristopherWalz** [comment]
> Do you have multiple dashboard tabs open? Why do you refresh the page? This would always trigger the rate limiting.
No, I only had 1 dashboard opened. I refreshed the page once after restarting the node and was logged out and couldn't log in again. Right now it seems to work again.

I'm using the default db engine, which seems to be rocksdb. I will keep an eye on the size used, but it already seems to decrease.
The rate limiting seems a little bit too strict for me tbh. Also it's weird, that the rate limiting is enabled when logged in as an admin. One logged in, why would there be a rate limiting? Why not just limit the login route?

**Comment by muXxer** [comment]
I already increased the limits locally. Will push it later.

Only the `/auth` route is limited. But if you refresh the dashboard page, the token in your browser is lost and the `/auth` route is called again. But that's something in the dashboard code, not in the hornet code. Refreshing isn't the way to go ;)
Just click on the home symbol instead.

**Comment by ChristopherWalz** [comment]
Pruning seems to be working, thanks again!
