### ISSUE TITLE
Raspberry Pi 4 4GB died with "auto" profile

### ISSUE THREAD

**Issue by muXxer** [iotaledger/hornet#38]
**Describe the bug**
Raspberry Pi 4 4GB died with "auto" profile due to OOM

**To Reproduce**
Let the node running for a while.

**Expected behavior**
Do not crash due to OOM.

**Environment information:**
 - OS: Raspbian
 - RAM: 4 GB
 - Cores: 4 Cores
 - Type: Raspberry Pi 4
 - HORNET version 0.2.6

**Additional context**
We have to modify the profile.

**Comment by muXxer** [comment]
https://pastebin.com/JiH7S0wp

**Comment by svenger87** [comment]
Profile "2gb" on this Pi which died with "Auto" doesn't cause oom

**Comment by svenger87** [comment]
Died also with 2gb profile. Sadly. 
See https://ghostbin.co/paste/x9cbe

Graphs could no be gathered.

**Comment by svenger87** [comment]
Problem for this specific machine (DietPi) is a 2GB tmpfs partition which reduces the free memory drastically.

**Comment by luca-moser** [comment]
Encountered also an OOM on my Raspi4 with 4GB: https://ybin.me/p/25d74972b64b5aa6#CPOBcj0KZRhsRVwJ/fIVNIPkXPBvtbUaJQsZMh0O2Us=

* it was still solidifying
* used profile `2gb`
* was syncing from a 4 days old LS file (4630 milestones)

perhaps we should note that people use the most recent LS file when using a low-end device.

**Comment by luca-moser** [comment]
Another OOM after 2 1/2 days (with 2gb profile) on the Raspi4 with 4GB: [log.txt](https://github.com/gohornet/hornet/files/3995037/log.txt)

**Comment by centercirclesolutions** [comment]
This seems to be due to the spent address load and syncing process which uses a lot of memory and logging. I was able to start a DietPi node with the '2gb' profile and then once synced restart it with the 'auto' profile which seems to be running fine at a much lower memory level. I'm not sure how to manage this as when hornet starts it looks like 4gb is available but once logging and badger memory usage increases the OOM error occurs.

**Comment by muXxer** [comment]
Solved with #199
