### ISSUE TITLE
CTPS affected by external spammer parameter

### ISSUE THREAD

**Issue by Nyrsta** [iotaledger/hornet#482]
**Luca-moser/ Iota-spammer can affect confirmation rate/Milestone by increasing instances parameter with same TPS output**

**To Reproduce**
- Run luca-moser/ iota-spammer on hornet node server in comnet (more then 1 server recommend)
- Set Instances much higher then number of cores of server (e.g. server 8, instances set at 50)
   ./spammer -node http://127.0.0.1:14265/ -mwm 10 -instances 50 -tag COMNET
- CTPS drops drastically until spammer stopped, after CTPS possibly catches up in next MS

**Expected behavior**
No decrease of CTPS

**Environment information:**
 - OS: Ubuntu 18.04 and 20.04
 - RAM: 32GB
 - Cores: 8
 - Type: Cloud VPS
 - HORNET RC13

**Additional context**
[hornet_SpamTest_Nyrsta.gz](https://github.com/gohornet/hornet/files/4732247/hornet_SpamTest_Nyrsta.gz)
[Screenshots.zip](https://github.com/gohornet/hornet/files/4732254/Screenshots.zip)

**Comment by muXxer** [comment]
Thanks for analyzing this problem.

It's not a problem of HORNET itself, but the tangle. It's a permissionless network, and everyone can issue transactions like he wants to. If the interconnections between the transactions are not optimal, you lower the confirmation rate of the tangle. So called lazy tips.
If you fire up so much instances, HORNET will return tips, but since you do so much things in parallel, these tips won't take the other new tx's into account. It's a client side problem.

Future improvements in the protocol (whiteflag, URTS) will improve these things eventually.
I guess the biggest boost in conf.rate regarding this problem would be, if the client libs would refresh the tips during PoW.
