### ISSUE TITLE
Spammer activity in the dashboard

### ISSUE THREAD

**Issue by FritzPeterAlbrecht** [iotaledger/hornet#49]
Can we have some information about the spammer. Like amount of tx or just any sign of activity, like "synced" it could be Spammer: active, workers 5, rate limit: 0.1 issued tps: 5

Would be cool, otherwise we have to search tangleexplorer to find our spam and check ift the spammer is running.

**Comment by ericvrp** [comment]
These are visible on the Misc page where you need to turn off other stats in the same graph because the spammer stats will be snowed under by it's tiny amount relative to the total number of transactions.

Disabling other stats is done by clicking on each of their names.

I think this issue can be closed for now.
