### ISSUE TITLE
Check messages to be semantically valid before adding to the tippool

### ISSUE THREAD

**Issue by muXxer** [iotaledger/hornet#797]
Check if we are doing this. Thibault reported he couldn't find it in the code, only in whiteflag.
In the RFC it was written that this should be done in tipselect as well.

**Comment by alexsporn** [comment]
I think this should be skipped. Syntax checks should be enough to verify the Message-Layer is valid.
Semantic checks of the payloads are done during white-flag, which is actually a layer above the Message-Layer.
For tip-selection we do not care about the payloads of the tips. If the syntax is valid and the URTS-threshholds are good, they should be used as tips. Worst thing that can happen is that they get marked as conflicting during the next white-flag.

I think the RFC should be changed here @Wollac

**Comment by GalRogozinski** [comment]
The idea IIRC was that honest tip-sel will not build on messages that are invalid (and thus garbage).
Obviously, marking them as `ignored` by white-flag will work as well, but it will lead to having a tangle with lots of garbage.

People can of course spam the tangle with useless, yet valid, garbage messages. So one can retort that it doesn't matter if we add semantically invalid messages to the tip pool because there's no real protection anyhow. But I still think that if there is a way we can avoid taxing nodes with messages that are garbage by definition then we should do it.

In the Chrysalis protocol group everyone agreed to it at least when the RFCs were written.

**Comment by Wollac** [comment]
I think this is something that got introduced when updating the RFC for Chrysalis; now we have payloads so the situation is different from just replacing bundles with messages..

We should definitely not accept syntactically invalid messages and this includes syntactic invalidity of contained _core_ payload types. If this is not fulfilled, messages "must not be broadcasted further and can be discarded right away" so they should not be included in the tip selection.

Semantic Validation is exactly what happens _during_ the actual white flag processing and according to the current RFCs signature checks are part of the semantic validation.

Therefore, I would propose to make clear in the white-flag RFC that we are only filtering out _syntactically_ invalid messages and core payloads!
(If for other reason, it would be super important to also filter invalid signatures, the sig checks would need be become part of the syntactic checks. And this would introduce some inconsistencies once the unlock blocks contain more complicated conditions than just signatures, so I'd maybe prefer to not do that.)

**Comment by alexsporn** [comment]
There is no way to do semantic validation outside of white-flag. And verifying each message against the current ledger for valid semantics will tax the node more and should be avoided

**Comment by Wollac** [comment]
> There is no way to do semantic validation outside of white-flag. And verifying each message against the current ledger for valid semantics will tax the node more and should be avoided

Yes 100%, full semantic validation is only well-defined in the context of white-flag so it is impossible (and unnecessary) to discard semantically invalid messages from the TSA!
However, as far as I understood this issue, it is exactly the question whether signature checks are actually semantic or syntax checks as they could be performed outside of white-flag.

**Comment by GalRogozinski** [comment]
Hmm @Wollac  
I think that in general we can say that analyzing the unlock block can have 3 outcomes:
- valid
- invalid
- unknown yet

Maybe we can just oust the invalid ones? I know Hornet at least used to verify signatures as soon as possible. If it is still the case (is it guys?), then it shouldn't be a big issue I believe

**Comment by Wollac** [comment]
Yes, this would be possible. However, as I have said, (trivial) signature validation would then become part of the syntactic checks, making it a very strange beast where sometimes and for certain unlock blocks the check is a syntax check and sometimes a semantic check. IMHO this would complicate the RFCs and the implementation.
So the question is, what benefits would this have to discard invalid sigs early? And is it worth it?

**Comment by GalRogozinski** [comment]
Benefits:
Will allow nodes to gossip less (we can optimize that invalid messages won't be gossiped). As a result nodes in general will have less sig validations to do. Syncing should have less validations. Invalid messages can also be pruned immediately.

Is it worth it?
This is probably a subjective question :man_shrugging:..  Let's maybe hear from the hornet devs what they think. Does it really complicate the implementation?

**Comment by alexsporn** [comment]
@luca-moser I think you should give input here, since this would actually be part of the iota.go validation

**Comment by Wollac** [comment]
> As a result nodes in general will have less sig validations to do.

I think we exactly had this discussion also in the TSA/protocol group call... We came to the conclusion, that it does not offer any protection against (DOS) attacks since an attacker can just issue transaction that are (semantically) invalid because of their inputs, but with valid signatures. In that case, they would still be gossiped and the expensive signatures validation would still be necessary. In fact, such an attack would _always_ be favorable compared to just issuing invalid sigs as they are much more expensive to validate and not much more expensive to create.
Such an approach would mostly help against accidentally invalid signatures and here it would IMHO make more sense to maybe check signatures as part of the API and reject transactions with invalid signatures there.
That's why I'd actually doubt that the number of transactions with invalid signatures would be significantly higher when they are not discarded.

**Comment by GalRogozinski** [comment]
Yup, it doesn't offer real protection against attacks for sure. It just takes care of cases that may happen accidentally.
This is why I think whether we should do it or not is very subjective.

**Comment by luca-moser** [comment]
Signature checks are semantic validation simply because the needed data to verify the signature might not be available while you've just received a message with a transaction (think inputs created within the same conf. cone).

I don't see any real benefits by trying to do signature verification outside of the white-flag confirmation.

**Comment by alexsporn** [comment]
Nothing to do here then.
