### ISSUE TITLE
Nodes crashes if stopped during Milestone Solidifying process

### ISSUE THREAD

**Issue by ghost** [iotaledger/hornet#90]
I find my node shut down due to some crash and the DB was corrupted (i couldn't restart the node).
I deleted the mainnetdb folder.
I restarted the node, loading the data from a local snapshot ( latest-export.gz.bin ).

After importing all data from snapshot, during the milestone solidifying process, i decided to stop the service ( systemctl stop GoHornet ) to catch the chance and change the TPSRateLimit of the spammer.

The node didn't shut down correctly and the process was killed for timeout.

![image](https://user-images.githubusercontent.com/10340922/71306532-c6508180-23e1-11ea-8d57-790b4b74cff9.png)
 
Now, database is corrupted again, after this forced kill.
I deleted the mainnetdb folder, restarted the Node service and everything is now running again.

OS: Linux Ubuntu 16.04
RAM: 16 GB
Cores: 6 Cores
Type: VPS Contabo
HORNET version 0.2.9

**Comment by IoTMOD** [comment]
What is `TimeoutStopSec` set to in your hornet systemd service?

**Comment by ghost** [comment]
I have no specific TimeoutStopSec setup. Is there any specific value to set up?

**Comment by IoTMOD** [comment]
Try to set `TimeoutStopSec=infinity` in your GoHornet.service
I'll close this issue as your DB got corrupted due to the fact the systemd service killed HORNET because it took to long for shutting down.
Anyway it seems HORNET got stuck.
So if you can reproduce this error with the new settings, please (re)open an issue.
