### ISSUE TITLE
Dashboard: Show version in footer

### ISSUE THREAD

**Issue by miili** [iotaledger/hornet#976]
A version string in the footer would be great.

**Comment by muXxer** [comment]
The dashboard already shows the version of the node, but only after you logged in, because this is sensitive info.
![image](https://user-images.githubusercontent.com/32371094/111828895-436fec80-88ec-11eb-9274-46f43fe3fe7d.png)
If you still want that feature, please create a new feature request in the node dashboard repository.
[Node-Dashboard](https://github.com/iotaledger/node-dashboard/tree/feature/chrysalis-pt2)
